### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by teamayu** [portapps/insomnia-portable#1]
According to your website/download info, it says the latest version is 7.0.3, but when you download it and install it, it says it's version 6.6.2.

![screenshot-25-10-2019_080538](https://user-images.githubusercontent.com/10624092/67533901-4ae29480-f6fe-11e9-92a7-98acfcfa5049.png)

**Comment by crazy-max** [comment]
No issue for me:

![image](https://user-images.githubusercontent.com/1951866/67587664-a7709e80-f754-11e9-8dc1-29be06a588e5.png)

Please create a proper [bug report](https://portapps.io/doc/reporting-issue/) using the [template](https://github.com/portapps/insomnia-portable/issues/new?template=bug_report.md).

**Comment by teamayu** [comment]
Doesn't make any sense. I've just tried again installing to a new folder. Clean install. Still says 6.6.2. 

I'll figure it out.

**Comment by crazy-max** [comment]
@teamayu Can you give me the download link?

**Comment by teamayu** [comment]
Max, I`ve figured it out. Actually, the send install was ok, I accessed the wrong file. For the previous install (and this appears to be the same for all the apps), is that there are two versions in the 'app' folder. So, if you download a new version to upgrade, it creates another entry in the 'app' folder. In the case of Insomnia:

app/app-6.6.2
app/app-7.0.3

And on launch it reads from the first available folder. When I deleted the 'app/app-6.6.2' folder it reverted to 7.0.3. So, all good.

**Comment by crazy-max** [comment]
Oh ok!

So you use the `7z` archive right? Because the setup remove the current `app` folder while upgrading.

**Comment by teamayu** [comment]
I always download the setup.exe file. Run it, select the same folder, but the previous version remains. Permissions problem?

**Comment by crazy-max** [comment]
Hum that's strange.

Can you reproduce and run the setup from the cmd like this `insomnia-portable-win64-7.0.3-12-setup.exe /LOG=install.log` and post the drag/drop the `install.log` here please?

**Comment by teamayu** [comment]
Sure, no problem. It will be on the next update though now as everything is up to date.

**Comment by crazy-max** [comment]
Ok I close for now
