### ISSUE TITLE
In some cases, requests cannot be sent normally and wait for requests continuously.

### ISSUE THREAD

**Issue by Sundaylog** [portapps/insomnia-portable#38]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
Please create proper [bug report](https://github.com/portapps/insomnia-portable/issues/new?assignees=&labels=&template=bug_report.md).
