### ISSUE TITLE
Using --user-data-dir does not work

### ISSUE THREAD

**Issue by simontom** [portapps/insomnia-portable#5]
### Behaviour
I'm trying to set the data-path.

Using shortcut in Windows:
"C:\portapps\insomnia-portable\app\app-7.1.1\Insomnia.exe --user-data-dir=C:\PROJECTS\Utils\InsomniaAppData"

Using insomnia-portable.yml file:
"
common:
  args:
  - --user-data-dir=C:\PROJECTS\Utils\InsomniaAppData
"

Tried to copy my app data right to the default data folder in insomnia-portable which worked like a charm. However, using --user-data-dir does not work and it is the way I'm currently trying to make it to work. 

#### Expected behaviour

> Insomnia should load the settings, workspaces, ...

#### Actual behaviour

> It does not load the app data from specified --user-data-dir.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
insomnia-portable-win64-7.1.1-17-setup.exe

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro x64

**Winver screenshot** :
![winver](https://user-images.githubusercontent.com/1636523/77185345-8fb60000-6ad1-11ea-9291-e8d924fccea6.png)

### Logs
[insomnia-portable.log](https://github.com/portapps/insomnia-portable/files/4360809/insomnia-portable.log)

**Comment by simontom** [comment]
Maybe I'm just using it wrong. Or setting it wrong.

**Comment by crazy-max** [comment]
> common:
>   args:
>   - --user-data-dir=C:\PROJECTS\Utils\InsomniaAppData

@simontom Don't specify `--user-data-dir` manually in the config file. It's already handled by the wrapper (data are pushed to `./data` folder).

**Comment by simontom** [comment]
Hi, sorry but I'm not 100% what you mean by that?
I thought it'd be possible to change the DATA folder path Insomnia-Portable uses.
Is that true or not? What is "--user-data-dir" for? Is that just some inner ARG which is not editable from outside?

I've already read https://portapps.io/app/insomnia-portable/ a few times but still not sure.
Sorry, I know I may sound pretty dumb but ...

**Comment by crazy-max** [comment]
@simontom Sorry my bad! Insomina is based on `"electron": "^3.1.2",` so `--user-data-dir` is not possible (available since Electron 5).

**Comment by crazy-max** [comment]
@simontom For apps based on Electron < 5, I [override the userData path](https://github.com/portapps/insomnia-portable/blob/2e67ab101d13bcafaa271ee949101f1fefb7fd4a/build.properties#L24-L26).

**Comment by simontom** [comment]
Oh, well then. So, it is overriden only inside your wrapper, right? Unable to change it from the outside additionally.

I have to admit, I solved it using folder symlink in the end.

**Comment by crazy-max** [comment]
@simontom Yes only symlink is good workaround for now.

**Comment by simontom** [comment]
Thank you very much for your time and help.
